version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-user-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - api-user-network
    restart: unless-stopped

volumes:
  sqlite_data:

networks:
  api-user-network:
    driver: bridge
